### ISSUE TITLE
fix the javascript generate button #hacktoberfest

### ISSUE THREAD

**Issue by ashutosh7i** [ashutosh7i/PasswordMan#18]
the generate button on index.php is not stable and displaces when page is resized, fix this simple issue by editing the inline css in file, Comment for assigning and details.

**Comment by IIITManjeet** [comment]
Kindly assign me this issue

**Comment by ashutosh7i** [comment]
done, Assigned to you

**Comment by ashutosh7i** [comment]
completed by @IIITManjeet
